version: "3"

services:
  navigateur:
    image: dorowu/ubuntu-desktop-lxde-vnc
    ports:      [ "8080:80" ]
    volumes:    [ "/dev/shm:/dev/shm" ]
    shm_size:   8g
    environment:
      - RESOLUTION=1920x1080

#  caddy:
#    image: caddy:latest
#    container_name: caddy
#    restart: unless-stopped
#    ports:
#      - "6667:80"
#    volumes:
#      - ./Caddyfile:/etc/caddy/Caddyfile
#    networks:
#      - internal

networks:
  internal:
