version: "3.9"

services:
  # ─────────────── Étape 0 : bootstrap Cloudflare ────────────────
  cf-bootstrap:
    build: ./cf-bootstrap
    environment:
      - DOMAIN=${DOMAIN}
      - CF_ACCOUNT_ID=${CF_ACCOUNT_ID}
      - CF_API_TOKEN=${CF_API_TOKEN}
    volumes:
      - cfshared:/shared
    networks: [desktopnet]
    restart: "no"

  # ─────────── Tunnel Cloudflare (remotely-managed) ──────────────
  cloudflared:
    image: cloudflare/cloudflared:latest
    depends_on:
      cf-bootstrap:
        condition: service_completed_successfully
      caddy:
        condition: service_started
    command: tunnel run --token-file /etc/cloudflared/token
    volumes:
      - cfshared:/etc/cloudflared   # token + config.yml
    networks: [desktopnet]
    restart: unless-stopped

  # ────────────────────────── Caddy ──────────────────────────────
  caddy:
    image: caddy:latest
    depends_on: [auth]
    expose: ["80"]                          # pas de port public
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks: [desktopnet]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      retries: 3

  # ─────────────────────────── Auth ───────────────────────────────
  auth:
    build: ./auth
    expose: ["8081"]
    environment:
      - LOGIN_USER=${LOGIN_USER}
      - LOGIN_PASS=${LOGIN_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_DOMAIN=${DOMAIN}
    networks: [desktopnet]
    restart: unless-stopped

  # ─────────────────────── noVNC desktop ─────────────────────────
  navigateur:
    image: dorowu/ubuntu-desktop-lxde-vnc:focal
    expose: ["80"]
    shm_size: 8g
    environment: ["RESOLUTION=1920x1080"]
    volumes: ["/dev/shm:/dev/shm"]
    networks: [desktopnet]

networks:
  desktopnet:

volumes:
  cfshared:
