services:
  navigateur:
    image: dorowu/ubuntu-desktop-lxde-vnc:focal
    expose: [ "80" ]
    volumes: [ "/dev/shm:/dev/shm" ]
    shm_size: 8g
    environment: [ "RESOLUTION=1920x1080" ]
    networks: [ desktopnet ]

  caddy:
    image: caddy:latest
    depends_on: [ navigateur ]
    ports:
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [ desktopnet ]

networks:
  desktopnet:
    name: desktopnet

volumes:
  caddy_data:
  caddy_config:
